parameters:
  environment:
  serviceConnectionName:
  params:

jobs:
  #Copy this -deployment when deploying to a new function and change:
  #Remember to add a new param to BuildAndDeploy.yaml
  #deployment, displayName, condition, appName, package (#)
  #Added retry because of know bug: https://github.com/microsoft/azure-pipelines-tasks/issues/15532

  - job: Deploy_FunctionApp_ActivityArea
    displayName: Deploy ActivityArea FA
    dependsOn: Deploy_Infrastructure
    condition: eq(${{parameters.params.deployActivityAreaFA}}, true)
    steps:
      - download: current
        artifact: drop
        displayName: Download drop
      - task: AzureFunctionApp@1
        displayName: "Deploy"
        retryCountOnTaskFailure: 4
        inputs:
          azureSubscription: ${{parameters.serviceConnectionName}}
          appType: functionApp
          appName: "func-${{lower(parameters.environment)}}-activityarea"
          package: "$(Pipeline.Workspace)/drop/publish/ActivityAreaFunctionApp.zip"
          appSettings: '-appsettingKey "$(AppSettingValueFromLibrary)"'

  - job: Deploy_FunctionApp_CommitteeArea
    displayName: Deploy CommitteeArea FA
    dependsOn: Deploy_Infrastructure
    condition: eq(${{parameters.params.deployCommitteeAreaFA}}, true)
    steps:
      - download: current
        artifact: drop
        displayName: Download drop
      - task: AzureFunctionApp@1
        displayName: "Deploy"
        retryCountOnTaskFailure: 4
        inputs:
          azureSubscription: ${{parameters.serviceConnectionName}}
          appType: functionApp
          appName: "func-${{lower(parameters.environment)}}-committeearea"
          package: "$(Pipeline.Workspace)/drop/publish/CommitteeAreaFunctionApp.zip"
          appSettings: '-appsettingKey "$(AppSettingValueFromLibrary)"'

  - job: Deploy_FunctionApp_CustomerArea
    displayName: Deploy CustomerArea FA
    dependsOn: Deploy_Infrastructure
    condition: eq(${{parameters.params.deployCustomerAreaFA}}, true)
    steps:
      - download: current
        artifact: drop
        displayName: Download drop
      - task: AzureFunctionApp@1
        displayName: "Deploy"
        retryCountOnTaskFailure: 4
        inputs:
          azureSubscription: ${{parameters.serviceConnectionName}}
          appType: functionApp
          appName: "func-${{lower(parameters.environment)}}-customerarea"
          package: "$(Pipeline.Workspace)/drop/publish/CustomerAreaFunctionApp.zip"
          appSettings: '-appsettingKey "$(AppSettingValueFromLibrary)"'

  - job: Deploy_FunctionApp_EconomyArea
    displayName: Deploy EconomyArea FA
    dependsOn: Deploy_Infrastructure
    condition: eq(${{parameters.params.deployEconomyAreaFA}}, true)
    steps:
      - download: current
        artifact: drop
        displayName: Download drop
      - task: AzureFunctionApp@1
        displayName: "Deploy"
        retryCountOnTaskFailure: 4
        inputs:
          azureSubscription: ${{parameters.serviceConnectionName}}
          appType: functionApp
          appName: "func-${{lower(parameters.environment)}}-economyarea"
          package: "$(Pipeline.Workspace)/drop/publish/EconomyAreaFunctionApp.zip"
          appSettings: '-appsettingKey "$(AppSettingValueFromLibrary)"'

  - job: Deploy_FunctionApp_EmploymentArea
    displayName: Deploy EmploymentArea FA
    dependsOn: Deploy_Infrastructure
    condition: eq(${{parameters.params.deployEmploymentAreaFA}}, true)
    steps:
      - download: current
        artifact: drop
        displayName: Download drop
      - task: AzureFunctionApp@1
        displayName: "Deploy"
        retryCountOnTaskFailure: 4
        inputs:
          azureSubscription: ${{parameters.serviceConnectionName}}
          appType: functionApp
          appName: "func-${{lower(parameters.environment)}}-employmentarea"
          package: "$(Pipeline.Workspace)/drop/publish/EmploymentAreaFunctionApp.zip"
          appSettings: '-appsettingKey "$(AppSettingValueFromLibrary)"'

  - job: Deploy_FunctionApp_EventArea
    displayName: Deploy EventArea FA
    dependsOn: Deploy_Infrastructure
    condition: eq(${{parameters.params.deployEventAreaFA}}, true)
    steps:
      - download: current
        artifact: drop
        displayName: Download drop
      - task: AzureFunctionApp@1
        displayName: "Deploy"
        retryCountOnTaskFailure: 4
        inputs:
          azureSubscription: ${{parameters.serviceConnectionName}}
          appType: functionApp
          appName: "func-${{lower(parameters.environment)}}-eventarea"
          package: "$(Pipeline.Workspace)/drop/publish/EventAreaFunctionApp.zip"
          appSettings: '-appsettingKey "$(AppSettingValueFromLibrary)"'

  - job: Deploy_FunctionApp_ProductArea
    displayName: Deploy ProductArea FA
    dependsOn: Deploy_Infrastructure
    condition: eq(${{parameters.params.deployProductAreaFA}}, true)
    steps:
      - download: current
        artifact: drop
        displayName: Download drop
      - task: AzureFunctionApp@1
        displayName: "Deploy"
        retryCountOnTaskFailure: 4
        inputs:
          azureSubscription: ${{parameters.serviceConnectionName}}
          appType: functionApp
          appName: "func-${{lower(parameters.environment)}}-productarea"
          package: "$(Pipeline.Workspace)/drop/publish/ProductAreaFunctionApp.zip"
          appSettings: '-appsettingKey "$(AppSettingValueFromLibrary)"'
