trigger: none
pr:
- master

pool:
  vmImage: 'ubuntu-latest'

name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  - name: BuildConfiguration
    value: 'release'
  - template: Dataverse/variables.yml

  ########################################################################################### 
  #######################################    BUILD    ####################################### 
  ###########################################################################################
stages:
  - stage: Build_Application
    displayName: Build 
    variables:
      - group: Dev
    jobs:
    - job: Build_And_Test
      displayName: Build and Test
      pool: 
        vmImage: "windows-latest"
      steps:
        - template: BuildSteps.yaml
